version: '3.7'
services:
  app:
    build:
      context: .
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "5174:5174" # remix dev server
    volumes:
      - ./:/app
      - ~/.bashrc:/root/.bashrc
